---
title: "datachallenge3: Coffee Ratings Data"
author: "menglu zhao"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')
library(tidyverse)
library(dplyr)
library(purrr)
library(knitr)
library(ggplot2)
library(Hmisc)
```
## Problem 1 Write a function that returns a table with the mean and standard deviation of the columns aroma through moisture of the coffee ratings data for different categories of coffee. Produce the table for (a) species, (b) country of origin, and (c) binned mean altitude in meters.

```{r}
coffee_clean <- coffee_ratings %>%
  filter(!is.na(altitude_mean_meters)) %>% # remove all the observation that dont have the altitude_mean_meters
  mutate(across(where(is.character), ~replace_na(., "Missing")),  # putting a 'Missing' for NAs
  altitude_binned = cut2(altitude_mean_meters, cuts = c(0, 1000, 2000, 3000, 4000)))  # binning the variable mean altitude by 1000 meters using cut2

group_vars <- c("species", "country_of_origin", "altitude_mean_meters") # these are the variables that we are interested in, and we want to generate a table for these variable.

selected_columns <- c("aroma", "flavor", "aftertaste", "acidity", "body", "balance", "uniformity", "clean_cup", "sweetness", "cupper_points", "moisture") # these are the variable that we want the mean and standard deviation of.

function1 <- function(data, group_var) {
  result <- data %>%
    group_by(across(all_of(group_var))) %>% # !! read the variables as column
    summarise(
      across( # this function apply the same action to multiple columns
        .cols = all_of(selected_columns), # specify the columns for summary
        .fns = list(mean = ~mean(., na.rm = TRUE), sd = ~sd(., na.rm = TRUE)) # a list of functions we want to use, in this case we want mean and standard deviation.
      )
    )
  return(result)
}

summaries <- map(c("species", "country_of_origin", "altitude_binned"), # these are the variables that we are interested in, and we want to generate a table for these variable.
                 ~function1(coffee_clean, .x) %>% # using the function we create
                   kable(caption = paste("Summary for", .x)))  # using kable to create tables
summaries
```

